services:
  strapi:
    container_name: strapi
    image: backend-strapi:latest # tobemodified
    restart: unless-stopped
    env_file: .strapi.env
    ports:
      - "3000:1337"
    depends_on:
      - postgres_db
    networks:
      - my-blog

  astro-web:
    container_name: astro-web
    image: frontend-astro:latest # tobemodified
    restart: unless-stopped
    env_file:
      - .astro.env
    ports:
      - "80:3000"
    networks:
      - my-blog

  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678 # tobemodified
    volumes:
      - ~/postgres/postgres-data:/var/lib/postgresql/data
      - ~/postgres/postgres-config:/etc/postgresql
    ports:
      - "5432:5432"
    networks:
      - my-blog

networks:
  my-blog:
    name: my-blog
    driver: bridge
